services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: hani
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: BD-auth-system
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://hani:123456@db:5432/BD-auth-system
    command: node server.js

volumes:
  db_data:
